### ISSUE TITLE
Using amp; instead of & in HTML

### ISSUE THREAD

**Issue by griffinlacek** [Egglestar/prj-rev-bwfs-dasmoto#1]
In HTML when using & it's best to use the HTML code & since the browser doesn't always know what & is inside of HTML. Check this out for more codes: http://www.html.am/html-codes/

https://github.com/Egglestar/prj-rev-bwfs-dasmoto/blob/master/ArtsAndCrafts/index.html#L5
https://github.com/Egglestar/prj-rev-bwfs-dasmoto/blob/master/ArtsAndCrafts/index.html#L10

**Comment by Egglestar** [comment]
Hey griffinlacek, thanks for your comment. 
I will use next time &amp; for the &-sign.
