### ISSUE TITLE
Using html in CSS

### ISSUE THREAD

**Issue by griffinlacek** [Egglestar/prj-rev-bwfs-dasmoto#4]
Nothing wrong with using html to set font-family for the page, but body is often used instead as it directly influences children elements. Here's a good discussion on this: https://css-tricks.com/html-vs-body-in-css/

https://github.com/Egglestar/prj-rev-bwfs-dasmoto/blob/master/ArtsAndCrafts/resources/css/index.css#L1-L3

**Comment by Egglestar** [comment]
ok got this thank you
