### ISSUE TITLE
Repeated font-family styles

### ISSUE THREAD

**Issue by griffinlacek** [Egglestar/prj-rev-bwfs-dasmoto#5]
Throughout your CSS you repeat font-family which could be set for the whole page by targeting body instead (you actually set it with html so none of the following styles are required). It's always good to reduce repetitions so that your code is cleaner and more maintainable!

https://github.com/Egglestar/prj-rev-bwfs-dasmoto/blob/master/ArtsAndCrafts/resources/css/index.css#L6
https://github.com/Egglestar/prj-rev-bwfs-dasmoto/blob/master/ArtsAndCrafts/resources/css/index.css#L13
https://github.com/Egglestar/prj-rev-bwfs-dasmoto/blob/master/ArtsAndCrafts/resources/css/index.css#L38

**Comment by Egglestar** [comment]
ok got this thx
