### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by griffinlacek** [Egglestar/prj-rev-bwfs-dasmoto#6]
**Grade:** Meets Expectations

**Summary:** This project is good! It closely meets the spec and the code is clean/free of any errors. One area of improvement would be trying to reduce repeated styles in your CSS for cleaner and more maintainable code!

As a further challenge, think about and try to change the page to have the item divs horizontally aligned instead of vertical aligned. There’s a few different ways to do this, but one way involves set widths and inline-block styling! This is a good resource for learning more: http://learnlayout.com/inline- block.html.

I’d also suggest checking out HTML codes, which will help explain my comment on the & usage in your HTML!

Good work!

**Comment by Egglestar** [comment]
Thank you for your comment and the suggestions. I will work on that.
